---
title: "Population Projection via Leslie Matrices"
author: "Corey Sparks, PhD"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(HMDHFDplus)
library(tidycensus)
```


```{r}
myusername <- userInput()
mypassword <- userInput() #1429845433
UShmd<- readHMDweb(item ="fltper_5x5", mypassword,myusername)
#49 for item, 51 for US

us_mort<-UShmd%>%
  filter(Year == 2015)

us_mort$qx[us_mort$Age==0]<-us_mort$qx[us_mort$Age==0]+us_mort$qx[us_mort$Age==1]
us_mort$Lx[us_mort$Age==0]<-us_mort$Lx[us_mort$Age==0]+us_mort$Lx[us_mort$Age==1]

us_mort<-us_mort[-2,]
  
head(us_mort)

UShfd<-readHFDweb(CNTRY="USA",username = myusername,password = 47515)
#30
us_fert<-UShfd%>%
  filter(Year==2015)%>%
  mutate(age_grp = cut(Age, breaks = seq(10, 55, 5), include.lowest = T))%>%
  group_by(age_grp)%>%
  summarise(asfr5 = sum(ASFR))%>%
  filter(is.na(age_grp)==F)%>%
  ungroup()
us_fert$age5<-seq(10,50,5)

us_dem<-merge(us_mort, us_fert, by.x="Age", by.y="age5", all.x=T)
us_dem$asfr5<-ifelse(is.na(us_dem$asfr5)==T, 0, us_dem$asfr5)

ggplot(us_dem)+geom_line( aes(x=Age, y=asfr5), color="red")+geom_line( aes(x=Age, y=qx), color="blue")+xlim(0, 110)+ylab("Rate")+xlab("Age")+theme_minimal()
  
us_popn<-get_estimates(geography="us", product = "characteristics", breakdown = c("AGEGROUP", "SEX"), year = 2015)
#Ages here https://www.census.gov/data/developers/data-sets/popest-popproj/popest/popest-vars.html
us_popn<-us_popn%>%
  filter(AGEGROUP>0&AGEGROUP<19, SEX==2)%>%
  #mutate(case_when(.$AGEGROUP==1))%>%
  arrange(AGEGROUP)
```

$$\begin{pmatrix}
n_1\\ 
n_2\\ 
n_3
\end{pmatrix} (t+1)=  
\begin{pmatrix}
F_1 & F_2 & F_3\\ 
P_1 & 0 & 0\\ 
0 & P_2 & 0
\end{pmatrix}
\begin{pmatrix}
n_1\\ 
n_2\\ 
n_3
\end{pmatrix}(t)$$


Or as:
$$n(t+1) = \mathbf{A} n(t)$$
### Leslie Matrix Constuction
```{r}

A<-matrix(0, nrow=dim(us_popn)[1], ncol=dim(us_popn)[1])
A
size<-dim(A)[1]
sxf1<-array(0,c(size-1))
Lxf<-us_dem$Lx/100000
for (i in 1:size-1){sxf1[i]<-(Lxf[i+1]/Lxf[i])}

#make matrix with survivals on off diagonal
sf1<-rbind(0,cbind(diag(sxf1),0))

##SPECIAL CALCULATION FOR OPEN-ENDED AGE GROUP OF LESLIE MATRICES
sf1[size,size]<-sf1[size,size-1]<-Lxf[size]/(Lxf[size]+Lxf[size-1])

ffab<-0.4882846
##MAKE THE LESLIE MATRICES FOR FEMALES
fert<-us_dem$asfr5/sum(us_dem$asfr5)

for(j in 1:size-1)
{sf1[1,j]<-(Lxf[1]/10)*(fert[j]+fert[j+1]*(sxf1[j]))*ffab}
sf1

sf1[size,size]<-0
A<-sf1
plot(x=seq(0, 80, 5), y=diag(sf1[-1,-ncol(sf1)]), type="l", ylim=c(0, 1), ylab="Rate", xlab="Age")
lines(x=seq(0, 80, 5), y = sf1[1, -size], col=2)
```

```{r}
##MAKE ARRAYS TO HOLD THE DATA
nproj<-10
newpop<-matrix(0, nrow=size, ncol=nproj)
newpop[,1]<-us_popn$value
for(i in 2:nproj){
newpop[,i]<-(A%*%newpop[,i-1])}
head(newpop)

options(scipen=999)
plot(y = apply(newpop, 2, sum), x= seq(2015, 2060, 5) , main="Total Female Population Size to 2060")
```


```{r}
library(demography)

library(StMoMo)
library(fds)
```

## data
```{r}
usdat<-hmd.mx(country = "USA", username = "corey.sparks@utsa.edu", password = "1429845433", label="USA")
usdatp<-hmd.pop(country = "USA", username = "corey.sparks@utsa.edu", password = "1429845433", label="USA")
#usdate<-hmd.e0(country = "USA", username = "corey.sparks@utsa.edu", password = "1429845433")

usdat<-extract.years(usdat, years=1940:2017)
usdatp<-extract.years(usdatp,years=1940:2017)
usdatm<-demogdata(data=usdat$rate$male,pop=usdat$pop$male,ages = usdat$age,years=usdat$year,label = usdat$label,name="male", type="mortality")

usdatf<-demogdata(data=usdat$rate$female,pop=usdat$pop$female,ages = usdat$age,years=usdat$year,label = usdat$label,name="female", type="mortality")


lca1<-lca(usdatm, max.age=90)
lca2<-lca(usdatf, max.age=90)

lca1<-fdm(usdatm, max.age=90, order = 3)
lca2<-fdm(usdatf, max.age=90)

plot(lca1)

plot(lca2)
#par(mfrow=c(1,2))
plot(usdatm,years=1940:2017,ylim=c(-11,1), ages = 50:70)
out1<-forecast(lca1,h=20,jumpchoice="fit")

plot(usdatf,years=1940:2017,ylim=c(-11,1), ages = 50:70)
out2<-forecast(lca2,h=20,jumpchoice="fit")

plot(forecast(lca1,h=20,jumpchoice="fit"),ylim=c(-11,1), )
lines(forecast(lca2,h=20,jumpchoice="fit"))

plot(out1)
plot(out2)
```

```{r}
AUSStMoMO <- StMoMoData(usdat,series = "male")
summary(AUSStMoMO)

D<-as.numeric(AUSStMoMO$Dxt)
E<-as.numeric(AUSStMoMO$Ext)
nage<-dim(AUSStMoMO$Dxt)[1]
nyear<-dim(AUSStMoMO$Dxt)[2]
age<-rep(AUSStMoMO$ages,nyear )
years<-rep(AUSStMoMO$years, nage)

dat<-data.frame(D=round(D,0), E=E, age=age, years=years)
dat$lr<-log(dat$D/dat$E)
library(mgcv)
fit1<-gam(lr~s(age)+years, family = gaussian,data= dat)
summary(fit1)

new<-expand.grid(age=seq(50,90,10), years=seq(2018, 2050,1))
new$est<-predict(fit1, newdata=new)
plot(y=new$est[new$age==60], x=new$years[new$age==60])
lines(y=new$est[new$age==70], x=new$years[new$age==70], col=2)
lines(y=new$est[new$age==80], x=new$years[new$age==80], col=3)

library(dplyr)
library(ggplot2)
new%>%
  ggplot(aes(x=age, y=est, group=years, color=years))+geom_line()


```


```{r}
Years <- 1933:2017
Age <- 1:111
d <- AUSStMoMO$Dxt
e <- AUSStMoMO$Ext
m <- d/e
m <- log(m)
n.x = nrow(m) # 111
n.y = ncol(m) # 85

m_mat <- matrix(m, nrow = n.x, ncol = n.y) # 111 X 85
plot(x=Age, y=m_mat[,1], type = "l") #mortality of all ages in year 1933
# Mean log mortality for all age groups under consideration (Age)
a_age <- rowMeans(m_mat)
lines(x = Age, y = a_age, col = 2)#average mortality for all age groups

# plotting mortality for Age = 65 as a trial run to see if code is working
# as exxpected
plot(x = Years, y = m_mat[65,], pch = 18, xlab = "Years", ylab = "log m", col = 2) #working!!!

# Average mortality across each year
a_year <- colMeans(m_mat)

#We need to estimate parameters ax, bx and kt of the Lee-Carter model
# ax is the avg of log mortality rates over time. ie sum(log m)/n.y
# avg of log rates -> a_hat <- rowSums(m)/94
# Subtracting a from all years in m_mat
m_hat <- matrix(1, nrow = n.y, ncol = n.x) #Dummy matrix with dim 85 X 111
m_hat <- t(m_mat)
m_mat <- t(m_mat)
for(i in 1:n.y) m_hat[,i] <- m_mat[,i] - a_age[i]
m_hat <- m_hat[,1:85]
age_mod <- 1:85
#SVD
svd_ <- svd(m_hat,1,1)
v <- svd_$v
u <- svd_$u
d <- svd_$d

b <- v/sum(v)
k <- u * sum(v) * d[1]
fit_1 = a_age[age_mod] + (b * k[1])
plot(x = age_mod, y = m_mat[1,age_mod], pch = 19, xlab = "Age", ylab = "m")
lines(x = age_mod, y = fit_1, col = 2, lwd = 2, xlab = "Age", ylab = "m")

fit_end <- a_age[age_mod] + (b * k[84])
plot(x = age_mod, y = m_mat[84,age_mod], pch = 18)
lines(x = age_mod, y = fit_end, col = 2, lwd = 2)

#Plotting parameter
par(mfrow = c(2,2))
plot(x = Years, y = k, type = "l")
plot(x = age_mod, y = a[age_mod], type = "l", xlab = "Ages", ylab = "ax")
plot(x = age_mod, y = b[age_mod], type = "l", xlab = "Ages", ylab = "bx" )
#plotting m over "Years"
plot(x = Years, y = m_mat[,1], pch = 19, ylab = "m", xlab = "Years", type = "l")
par(mfrow = c(1,1))

########################################################################################
##Performing SVD over ages 40:90
Age_new <- 40:90
m_mat_new <- m_mat[,Age_new]
m_hat_new <- m_hat[,Age_new]
n_x <- nrow(m_hat_new)
n_y <- ncol(m_hat_new)

for(i in 1:n_y) m_hat_new[,i] <- m_mat[,i] - a_age[i]

#SVD
svd_ <- svd(m_hat_new,1,1)
v_1 <- svd_$v
u_1 <- svd_$u
d_1 <- svd_$d

b_1 <- v_1/sum(v_1)
k_1 <- u_1 * sum(v_1) * d_1[1]
fit_1_new = a_age[Age_new] + (b_1 * k_1[1])
plot(x = Age_new, y = m_mat_new[1,], pch = 19, xlab = "Age", ylab = "m")
lines(x = Age_new, y = fit_1_new, col = 2, lwd = 2)

fit_end_new <- a_age[Age_new] + (b_1 * k_1[84])
plot(x = Age_new, y = m_mat_new[84,], pch = 18, xlab = "Age", ylab = "m")
lines(x = Age_new, y = fit_end_new, col = 2, lwd = 2)

#Plotting parameter
par(mfrow = c(2,2))
plot(x = Years, y = k_1, type = "l",  type = "l", xlab = "Years", ylab = "k")
plot(x = Age_new, y = a_age[Age_new], type = "l", type = "l", xlab = "Ages", ylab = "ax")
plot(x = Age_new, y = b_1, type = "l",  type = "l", xlab = "Ages", ylab = "bx")
par(mfrow = c(1,1))

############################################################################################
#Forecasting
#Initialising a dummy matrix to hold our simulation of random walk
#for kt
library(ggplot2)
S <- matrix(0,61,100)

for(j in 1:100) S[,j] <- -54.3332 + cumsum(-0.75 + rnorm(61, 0, 0.75))

quan <- function(x) quantile(x, c(0.05,0.5, 0.95))
sim <- apply(S, 1, quan)

##Forecast of kt showing 5%,50% and 95% confidence intervals of the random walk.
#plot(x = Years, y = k_1, xlab = "Years",type = "l", ylab = "k",
#     xlim = c(1920,2064), ylim = c(-90,50))
#lines(x = 2014:2074, y = sim[1,], col = 4, lty = "dashed")
#lines(x = 2014:2074, y = sim[2,], col = 2, lty = "dotted")
#lines(x = 2014:2074, y = sim[3,], col = 4, lty = "dashed")

ggplot() +
  xlim(1920,2064) +
  ylim(-90,50) +
  geom_line(data = NULL, aes(x = Years, y = k_1)) +
  geom_line(data = NULL, aes(x = 2014:2074, y = sim[1,]), col = 2) +
  geom_line(data = NULL, aes(x = 2014:2074, y = sim[2,]), col = 4) +
  geom_line(data = NULL, aes(x = 2014:2074, y = sim[3,]), col = 2)
  

# LC with StMoMo-----
# Extracting male and female dat from HMD, after creating a StMoMo data object
# "Male" and "Female" data are assigned to different variables for easier
# data wrangling.
library(colorspace)
library(gridExtra)
library(cowplot)
library(RColorBrewer)

usdat<-hmd.mx(country = "USA", username = "corey.sparks@utsa.edu", password = "1429845433", label="USA")
AUSStMoMO_m <- StMoMoData(usdat,series = "male")
AUSStMoMO_f <- StMoMoData(usdat,series = "female")

#Under a Binomial setting
#Becasue I'm opting to use the data with the Lee-Carter model under a Binomial setting
#the exposures have to be converted to the initial exposures.
LC1 <- lc(link = "logit")
data_m <- central2initial(AUSStMoMO_m)
data_f <- central2initial(AUSStMoMO_f)
ages_fit <- 40:90


#This can be ussed ot generate a weight matrix over the ages and years in the data.
# clips = 1 assigns 0 weights to the first and last cohorts.
wxt_m <- genWeightMat(ages = ages_fit, years = data_m$years,
                     clip = 1)
wxt_f <- genWeightMat(ages = ages_fit, years = data_f$years,
                      clip = 1)

#For males
LCfit_m <- fit(LC1, data = data_m, ages.fit = ages_fit, wxt = wxt_m)

#For females
LCfit_f <- fit(LC1, data = data_f, ages.fit = ages_fit, wxt = wxt_f)

#plotting parameters
par(mfrow = c(1,3))
plot(x = ages_fit, y = LCfit_m$ax, col = 2, type = "l")     #males
lines(x = ages_fit, y = LCfit_f$ax, col = 4)     #females

plot(x = ages_fit, y = LCfit_m$bx, col = 2, type = "l")
lines(x = ages_fit, y = LCfit_f$bx, col = 4)

plot(x = Years, y = LCfit_m$kt[1,], col = 2, type = "l")
lines(x = Years, y = LCfit_f$kt[1,], col = 4)
par(mfrow = c(1,1))

#Goodness-of-fit analysis-----
# For males
res_m <- residuals(LCfit_m)
aic_ <- AIC(LCfit_m)
bic_ <- BIC(LCfit_m)
aic_
bic_
#For females
res_f <- residuals(LCfit_f)

#Plotting colour maps of males and females
p1 <- plot(res_m, type = "colourmap", main = "Residuals of Male data")
p2 <- plot(res_f, type = "colourmap", main = "Residuals of Female data")

#Plotting residuals of males and females
pal <-RColorBrewer::brewer.pal(4,"Greys")
plot(res_m, type = "scatter", col = pal)
plot(res_f, type = "scatter", col = pal)

#Forecasting----
LCfore_m <- forecast(LCfit_m, h = 50)
LCfore_f <- forecast(LCfit_f, h = 50) 

## Comparison of forcasting done in three instances:
# a.) Forecasting kt with random walk using the forecast funciton.
# b.) Forecast of kt done with SVD and first principles.
# c.) Forecast of kf done with forecast and iarima.
par(mfrow=c(1,3))
plot(x = Years, y = LCfit_m$kt[1,], type = "l", xlim = c(1920,2065),
     ylim = c(-70,20), sub = "a)", ylab = "kt")
lines(x = 2014:2063, y = LCfore_m$kt.f$mean, col = 2)
lines(x = 2014:2063, y = LCfore_m$kt.f$upper[1,,1], col = 4)
lines(x = 2014:2063, y = LCfore_m$kt.f$lower[1,,1], col = 4)

plot(x = Years, y = k_1, xlab = "Years",type = "l", ylab = "kt",
     xlim = c(1920,2064), ylim = c(-90,50), sub = "b)")
lines(x = 2014:2074, y = sim[1,], col = 4, lty = "dashed")
lines(x = 2014:2074, y = sim[2,], col = 2, lty = "dotted")
lines(x = 2014:2074, y = sim[3,], col = 4, lty = "dashed")

LCforeArima <- forecast(LCfit_m, h = 50, kt.method = "iarima",
                        kt.order = c(1, 1, 2))

plot(LCforeArima, only.kt = TRUE, sub = "c)")
par(mfrow=c(1,1))

## Simulation for LC
LCsim_m <- simulate(LCfit_m, nsim = 500, h = 50)
LCsim_f <- simulate(LCfit_f, nsim = 500, h = 50)

#Simulation of kt for males and females
par(mfrow=c(1,2))
plot(x = Years, y = LCfit_m$kt, ylim = range(LCfit_m$kt,LCsim_m$kt.s$sim[1, , 1:20]),
     xlim = range(LCfit_m$years, LCsim_m$kt.s$years), type = "l")
matlines(LCsim_m$kt.s$years, LCsim_m$kt.s$sim[1, , 1:20], type = "l", lty = 1)

plot(x = Years, y = LCfit_f$kt, ylim = range(LCfit_f$kt,LCsim_f$kt.s$sim[1, , 1:20]),
     xlim = range(LCfit_f$years, LCsim_f$kt.s$years), type = "l")
matlines(LCsim_f$kt.s$years, LCsim_f$kt.s$sim[1, , 1:20], type = "l", lty = 1)
par(mfrow=c(1,1))


f<-data_f$Dxt/data_f$Ext 

m<-data_m$Dxt/data_m$Ext 

#Simulation of mortality for males
par(mfrow=c(1,2))
a_ <- range(m[75, ], LCsim_m$rates[35, , 1:20])
b_ <- range(f[75, ], LCsim_f$rates[35, , 1:20])
plot(LCfit_m$years, exp(m[75, ]), xlim = range(LCfit_m$years, LCsim_m$years),
       ylim = c(0.001,0.09) ,type = "l",
      xlab = "year", ylab = "rate", main = "Male mortality rates at age 75")
matlines(LCsim_m$years, LCsim_m$rates[35, , 1:20], type = "l", lty = 1)
  
plot(LCfit_f$years, f[75, ], xlim = range(LCfit_f$years, LCsim_f$years),
     ylim = b_ ,type = "l",
     xlab = "year", ylab = "rate", main = "Female mortality rates at age 75")
matlines(LCsim_f$years, LCsim_f$rates[35, , 1:20], type = "l", lty = 1)
par(mfrow=c(1,1))

#Research-----
y_ <- 40:80
ag_ <- 1:94
lin_mod <- lm(m[y_,]~y_)
plot(lin_mod)
pr.lm <- predict(lin_mod)
plot(pr.lm[1,])


plot(m[40:80,1], col = 2, pch = 19, ylim = c(-7,-2))
points(m[40:80,94], pch = 19, col = 4)

matplot(m[40:80,], col = pal, type = "l")
matlines(m[40:80,94], col = pal, pch = 19)
```


